### PR TITLE
Fix: rm/uninstall not working when 'v' is missing for neovim versions.

### LINKED ISSUE #224: Error: rm/uninstall/remove is not working as intended
Hey there, 
I caught this issue with rm. Whenever you do not pass the 'v' to the command it fails to handle it properly.

As opposed to:
image

Potentially, as a long term fix, I think you could add a field true_dir_name to the ParsedVersion struct
image

### PR DESCRIPTION
**Pull request by matdexir**
fixes #224 
Let me know what you think!

### CODE REVIEW

**Comment by MordechaiHadad** [comment]
Although this solution seems fine enough, why not switch it to `tag_name` instead of the `non_parsed_string`?

**Comment by matdexir** [comment]
@MordechaiHadad 
That was actually my first thought but I just left it as is because I was afraid of breaking compatibility with nightly/commit based directories. I was afraid that it might break them

**Comment by MordechaiHadad** [comment]
> @MordechaiHadad That was actually my first thought but I just left it as is because I was afraid of breaking compatibility with nightly/commit based directories. I am not too sure how they work since I did not dive deep into that part of the code

Fair enough then, fix the clippy errors and done.

Another way is just add

**Comment by matdexir** [comment]
should be fixed now!

**Pull request merged**
