### PR TITLE
Fix capacity overflow for list command

### PR DESCRIPTION
**Pull request by MordechaiHadad**

### CODE REVIEW

**Comment by Amar1729** [comment]
Hm, no dice:

```
❯  ./target/debug/bob list
┌───────────┬─────────────┐
│  Version  │  Status     │
├───────────┼─────────────┤
│  v0.9.0   │  Installed  │
│  nightly  │  Used       │
thread 'main' panicked at src/handlers/list_handler.rs:56:26:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looks like I have `nightly-5651c1f` installed. its `path_name.len()` is `15`, which is causing an overflow with `version_max_len - path_name.len()` (`7 - 15`).

If i set `version_max_len = 16` explicitly it prints out fine. I'm not sure how `5651c1f` got installed, but it doesn't match the regex in `src/helpers/version/nightly.rs`, which specifies _8_ hex chars. I changed it to `nightly-[a-zA-Z0-9]{7,8}`, which matches the version i have downloaded properly and results in `version_max_len` being properly set to `16`.

However I'm not sure what's the right approach here? Should the rollback nightly regex be loosened?

**Comment by MordechaiHadad** [comment]
anything from this commit?

**Comment by sungyoonc** [comment]
The code expects the hash after `nightly-` to be 8 characters, but the created nightly rollbacks have 7 character after `nightly-`.
The command `bob list` and `bob rollback` works when I change the directory name from `nightly-ec74538` to `nightly-ec74538f`.

In src/handlers/list_handler.rs
```rust
let alphanumeric_regex = Regex::new(r"^[a-zA-Z0-9]{8}$").unwrap();
```
Also at `produce_nightly_vec()` in src/helpers/version/nightly.rs (for rollback command)
```rust
let regex = Regex::new(r"nightly-[a-zA-Z0-9]{8}")?;
```

**Comment by MordechaiHadad** [comment]
> The code expects the hash after `nightly-` to be 8 characters, but the created nightly rollbacks have 7 character after `nightly-`. The command `bob list` and `bob rollback` works when I change the directory name from `nightly-ec74538` to `nightly-ec74538f`.
> 
> In src/handlers/list_handler.rs
> 
> ```rust
> let alphanumeric_regex = Regex::new(r"^[a-zA-Z0-9]{8}$").unwrap();
> ```
> 
> Also at `produce_nightly_vec()` in src/helpers/version/nightly.rs (for rollback command)
> 
> ```rust
> let regex = Regex::new(r"nightly-[a-zA-Z0-9]{8}")?;
> ```

Ye I accidentally fucked it up, it used to generate it's own hash until i changed that and forgot to update, @Amar1729 is it better now? works for me when using both rollback with 7 and 8 characters after.

**Comment by Amar1729** [comment]
@MordechaiHadad forgot to reply, my bad. Yeah, seems like that works for me!

```
❯  ./target/debug/bob list
┌────────────────────┬─────────────┐
│  Version           │  Status     │
├────────────────────┼─────────────┤
│  v0.9.0            │  Installed  │
│  nightly           │  Used       │
│  nightly-5651c1f   │  Installed  │
│  v0.9.4            │  Installed  │
└────────────────────┴─────────────┘
```

**Pull request merged**
