### PR TITLE
feat(cli): add `complete [shell]` subcommand for tab-completion gen

### PR DESCRIPTION
**Pull request by utilyre**
At first I wanted to generate the completion files at compile time and then `include_str!` them in the binary (so that I could avoid adding yet another dependency), but that brought a lot of complexity into the code base which was completely unnecessary plus it made it impossible to access the `clap_complete::Shell` enum directly in the `Cli` enum.

Anyhow, I can do that if that seems to be a better option.

### CODE REVIEW

**Comment by MordechaiHadad** [comment]
@utilyre is that basically a subcommand auto complete or?

**Comment by utilyre** [comment]
> @utilyre is that basically a subcommand auto complete or?

It generates a completion script that you can put somewhere (depending on your shell) and get tab completion for the utility. This is a common subcommand among CLI apps. `rustup completions -h` gives a great explanation.

**Comment by utilyre** [comment]
I've just pushed a commit that explains the whole shell completion thing setup on the readme.

**Comment by MordechaiHadad** [comment]
Looks awesome thanks!

**Pull request merged**
