### PR TITLE
Add aarch64-unknown-linux-gnu build

### PR DESCRIPTION
**Pull request by 0atman**
Not tested this, but I am hopeful that this is all that might be needed to build aarch64-linux binaries for M1!

### CODE REVIEW

**Comment by 0atman** [comment]
POSSIBLY fixes #91

**Comment by MordechaiHadad** [comment]
@0atman will need you to fix the failed compilation for aarch, also it would be better imo if you rename it to arm64 from m1 since it will work on arm linux machines

**Comment by MordechaiHadad** [comment]
@0atman To fix t his error simply add installing `aarch64-linux-gnu-gcc` since it's an ubuntu machine running the CI/CD you probably simply need to add `sudo apt install aarch64-linux-gnu-gcc`

**Comment by MordechaiHadad** [comment]
bruh, it always fails no matter what.... gonna look into it more.

**Comment by 0atman** [comment]
So sorry I wasn't able to help here - This is incredible news! 
Thank you so much for your work on this project, do you have a sponsor page I'd like to contribute :-)

**Comment by MordechaiHadad** [comment]
what's a sponsor page

**Comment by 0atman** [comment]
Fantastic, I'm sponsoring, thank you for your work here!

**Comment by MordechaiHadad** [comment]
> Fantastic, I'm sponsoring, thank you for your work here!

holy fuck, I am speechless

**Pull request merged**
