### PR TITLE
docs(README): mention `bob` AUR package

### PR DESCRIPTION
**Pull request by orhun**
Hello!

I packaged `bob` for Arch Linux in the AUR:

- https://aur.archlinux.org/packages/bob

This PR updates README.md to reflect this 🐻

### CODE REVIEW

**Comment by MordechaiHadad** [comment]
@orhun hey that's very cool of you!
I do have a question tho why not call it `bob-git` or something as there is already `bob-bin`

**Comment by MordechaiHadad** [comment]
btw nice PR number.

**Comment by orhun** [comment]
> @orhun hey that's very cool of you! I do have a question tho why not call it `bob-git` or something as there is already `bob-bin`

- `bob-bin`: installs the latest upstream binary
- `bob`: compiles the latest release from source
- `bob-git` (doesn't exist): compiles from the last commit

> btw nice PR number.

Hell yeah!

**Comment by MordechaiHadad** [comment]
@orhun Oh I see

**Pull request merged**
