### PR TITLE
Fix version installation bug for MacOS

### LINKED ISSUE #32: MacBook M1 Pro install problem
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/modules/expand_archive.rs:12:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
image

### PR DESCRIPTION
**Pull request by MordechaiHadad**
Fix #32

### CODE REVIEW

**Comment by mrxiaozhuox** [comment]
image
I can't build it.

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox don't build it yourself, use the CI builds

**Comment by mrxiaozhuox** [comment]
> @mrxiaozhuox don't build it yourself, use the CI builds

Online CI environment ?

**Comment by MordechaiHadad** [comment]
> > @mrxiaozhuox don't build it yourself, use the CI builds
> 
> Online CI environment ?

https://github.com/MordechaiHadad/bob/actions/runs/2868520978 the macos build here

**Comment by mrxiaozhuox** [comment]
have same problem.
image

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox damn weird, It was supposed to actually give a ""better"" error in the new build, will have to look into this more.
Sorry for the late response.

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox could you try to use the new CI build? 
Sorry my changes are incredibly slow, it's not very easy to figure out the issue without having a machine to test it on 😅

**Comment by mrxiaozhuox** [comment]
image

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox now I am even more confused... I didn't really fix anything.
Did you change anything in your setup?

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox shouldnt really matter
Can you run `bob erase` and then run `bob stable`

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox any update?

**Comment by mrxiaozhuox** [comment]
image

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox huh this is weird. erase shouldn't change the bob installation itself, will have to look into this too.
Is 0.7.2 really used?
those are some weird bugs.

**Comment by mrxiaozhuox** [comment]
I have a 0.7.2 install from neovim office package (but it has nothing to do with this bug)

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox oh alright
Can you uninstall neovim package when using bob and reinstall when you need it back?

**Comment by mrxiaozhuox** [comment]
you mean I need uninstall my 0.7.2?

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox yeah in order for bob to work seamlessly you need to uninstall neovim that isn't managed by bob.

**Comment by mrxiaozhuox** [comment]
Because the bob is not work on my Mac, so I install from office.

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox doesn't work as in just installing a version or is it also when u run `bob use <version>` neovim isnt in path?

**Comment by mrxiaozhuox** [comment]
very strange.
image

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox that is indeed very strange lol
I have changed nearly nothing 
Can you retry using the latest release of bob again?

**Pull request merged**
